version: '3.8'
services:
  api:
    build: ./api
    container_name: api_c
    image: my-api
    ports:
      - "4000:4000"
    volumes:
      - ./api:/app
      - ./app/node_modules
  myblog:
    build: ./myblog
    container_name: myblog_c
    image: myblog
    ports:
      - '3000:3000'
    # volumes:
    #   - ./myblog:/app
    #   - ./app/node_modules

    stdin_open: True
    tty: True
    

